{{- if .Values.hpa}}
{{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else if .Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
apiVersion: autoscaling/v2beta2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gitlab-runner.fullname" . }}
  minReplicas: {{ default 1 .Values.hpa.minReplicas }}
  maxReplicas: {{ default 1 .Values.hpa.maxReplicas }}
  metrics:
{{ toYaml .Values.hpa.metrics | indent 2 }}
{{- end}}
