{{- if eq (include "gitlab-runner.isSessionServerAllowed" . ) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-runner.fullname" . }}-session-server
  namespace: {{ .Release.Namespace | quote }}
  {{- if .Values.sessionServer.annotations }}
  annotations:
    {{- toYaml .Values.sessionServer.annotations | nindent 4 }}
  {{- end }}
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ include "gitlab-runner.fullname" . }}
    release: "{{ .Release.Name }}"
  type: {{ (eq (include "gitlab-runner.server-session-service-type" .) "Headless") | ternary "ClusterIP" (include "gitlab-runner.server-session-service-type" .) }}
  {{- if eq (include "gitlab-runner.server-session-service-type" .) "LoadBalancer"}}
  {{- if .Values.sessionServer.publicIP }}
  loadBalancerIP: {{ .Values.sessionServer.publicIP }}
  {{- end }}
  {{- if .Values.sessionServer.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.sessionServer.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- if eq (include "gitlab-runner.server-session-service-type" .) "Headless" }}
  clusterIP: None
  {{- end }}
  ports:
  - protocol: TCP
    port: {{ include "gitlab-runner.server-session-external-port" . }}
    targetPort: {{ include "gitlab-runner.server-session-internal-port" . }}
    {{- if .Values.sessionServer.nodePort }}
    nodePort: {{ .Values.sessionServer.nodePort }}
    {{- end }}
{{- end }}
