# Default values for gitaly.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  gitaly:
    enabled: true
    internal:
      names: ["default"]
    external: []
    authToken: {}
    hooks: {}
  # serviceName:
  redis:
    auth: {}

gitaly: {}
# serviceName:

internal: {}
image:
  repository: registry.gitlab.com/gitlab-org/build/cng/gitaly
  # pullPolicy: IfNotPresent
  # pullSecrets: []
  # tag: master
service:
  tls: {}
  type: ClusterIP
  clusterIP: None
annotations: {}
common:
  labels: {}
podLabels: {}
serviceLabels: {}

init:
  image: {}
    # repository:
    # tag:
  resources:
    requests:
      cpu: 50m
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop: [ "ALL" ]

# Gitaly built-in cgroups, spawns Git processes into a cgroup per repository, protecting the service/pod from OOM events
# ref: https://docs.gitlab.com/ee/administration/gitaly/configure_gitaly.html#control-groups
cgroups:
  enabled: false
  initContainer:
    image:
      repository: registry.gitlab.com/gitlab-org/build/cng/gitaly-init-cgroups
    securityContext:
      runAsUser: 0
      runAsGroup: 0
  mountpoint: '{% file.Read "/etc/gitlab-secrets/gitaly-pod-cgroup" | strings.TrimSpace %}'
  hierarchyRoot: gitaly
  # memoryBytes:
  # cpuShares:
  # cpuQuotaUs:
  repositories: {}
    # count:
    # memoryBytes:
    # cpuShares:
    # cpuQuotaUs:
    # maxCgroupsPerRepo:

## Support for tolerations for pod scheduling
tolerations: []

## The Gitaly StatefulSet's priorityClassName
# priorityClassName:

# Gitaly shutdown grace period, how long to wait for in-flight requests to complete (seconds)
# Pod `terminationGracePeriodSeconds` is set to this value + 5 seconds
gracefulRestartTimeout: 25

logging:
  format: "json"
  # level:
  # sentryDsn:
  # sentryEnvironment:

git: {}
  # catFileCacheSize:
  ## Amend the default configuration Gitaly is using when spawning Git
  ## commands. Accepts configuration as documented in git-config(1).
  # config:
  #   - {key: "pack.threads", value: 4}

prometheus: {}
  # grpcLatencyBuckets: "[1.0, 1.5, 2.0, 2.5]"

workhorse: {}
  # by default, Workhorse is a part of the Webservice Pods / Service
  # scheme: 'http'
  # host: '0.0.0.0'
  # serviceName: 'webservice'
  # port: 8181
shell:
  authToken: {}
  concurrency: []
    # - rpc: "/gitaly.SmartHTTPService/PostUploadPack"
    #   maxPerRepo: 20
    # - rpc: "/gitaly.SSHService/SSHUploadPack"
    #   maxPerRepo: 20

## Enable prometheus metrics and set the port to scrape the
## container on.
metrics:
  enabled: true
  port: 9236
  path: /metrics
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    endpointConfig: {}
  # DEPRECATED in favor of `metrics.port` as seen above
  metricsPort:

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true

  ## git repositories Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  accessMode: ReadWriteOnce
  size: 50Gi

  ## If subPath is set mount a sub folder of a volume instead of the root of the volume.
  ## This is especially handy for volume plugins that don't natively support sub mounting (like glusterfs).
  ##
  subPath: ""

  ## Only bind to a volume with the following exactly matched labels with values.
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
  matchLabels: {}

  ## Only bind to a volume with the following exppression matched labels.
  ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
  matchExpressions: []
  annotations: {}
  labels: {}

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
    cpu: 100m
    memory: 200Mi

## For PodDisruptionBudget, how many pods can be unavailable at one time
maxUnavailable: 1

## Allow to overwrite under which User and Group Pod will be running.
securityContext:
  runAsUser: 1000
  fsGroup: 1000
  # fsGroupChangePolicy: OnRootMismatch

## Allow to overwrite the specific security context under which the gitaly container is running.
containerSecurityContext:
  runAsUser: 1000
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: ["ALL"]

## Enable deployment to use a serviceAccount
serviceAccount:
  enabled: false
  create: false
  annotations: {}
  ## Used for local override of global ServiceAccount token mounting
  # automountServiceAccountToken: false
  ## Name to be used for serviceAccount, otherwise defaults to chart fullname
  # name:

statefulset:
  strategy: {}
  livenessProbe:
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 3
  startupProbe:
    enabled: true
    initialDelaySeconds: 1
    periodSeconds: 1
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 60

affinity:
  podAntiAffinity:
    topologyKey:
  nodeAffinity:
       key:
       values:

## Enable the Gitaly pack-objects cache
## ref: https://docs.gitlab.com/ee/administration/gitaly/configure_gitaly.html#pack-objects-cache
packObjectsCache: {}
#  enabled: false
#  dir: "/home/git/repositories/+gitaly/PackObjectsCache"
#  max_age: 5m

## Enable Gitaly to GPG sign all commits created by GitLab
## ref: https://docs.gitlab.com/ee/administration/gitaly/configure_gitaly.html#configure-commit-signing-for-gitlab-ui-commits
gpgSigning: {}
  # enabled: false
  # secret: glGPG
  # key:

backup: {}
  # goCloudUrl:

# default enable gomemlimit to avoid gc related OOM errors
gomemlimit:
  enabled: true
