apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-zoekt.backendSvc" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab-zoekt.labels" . | nindent 4 }}
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
    {{- include "gitlab.serviceLabels" . | nindent 4 }}
  {{- with .Values.serviceBackend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.gateway.listen.port}}
    name: gateway
  selector:
    {{- include "gitlab-zoekt.selectorLabels" . | nindent 4 }}