crio_registries_mirrors:
  - prefix: docker.io
    insecure: false
    blocked: false
    location: registry-1.docker.io
    mirrors:
      # - location: 192.168.100.100:5000
      #   insecure: true
      - location: mirror.gcr.io
        insecure: false
