data:
  configure: |
    set -e
    mkdir -p /init-secrets/gitaly /init-secrets/shell
    cp -v -r -L /init-config/.gitlab_shell_secret  /init-secrets/shell/.gitlab_shell_secret
    cp -v -r -L /init-config/gitaly_token  /init-secrets/gitaly/gitaly_token
    {{- if $.Values.global.gitaly.tls.enabled }}
    cp -v -L /init-config/gitaly.crt /init-secrets/gitaly/gitaly.crt
    cp -v -L /init-config/gitaly.key /init-secrets/gitaly/gitaly.key
    {{- end }}
    {{- if .Values.gpgSigning.enabled }}
    cp -v -L /init-config/signing_key.gpg  /init-secrets/gitaly/signing_key.gpg
    {{- end }}
  config.toml.tpl: |
    # The directory where Gitaly's executables are stored
    bin_dir = "/usr/local/bin"

    # listen on a TCP socket. This is insecure (no authentication)
    listen_addr = "0.0.0.0:{{ coalesce .Values.service.internalPort .Values.global.gitaly.service.internalPort }}"

    # Directory where internal sockets reside
    # note: no value will result in a `/tmp/gitlab-internal-*` path
    # internal_socket_dir = "/home/git"

    {{- if $.Values.global.gitaly.tls.enabled }}
    tls_listen_addr = "0.0.0.0:{{ coalesce .Values.service.tls.internalPort .Values.global.gitaly.service.tls.internalPort }}"
    {{- end }}

    # If metrics collection is enabled, inform gitaly about that
    {{- if .Values.metrics.enabled }}
    prometheus_listen_addr = "0.0.0.0:{{ default .Values.metrics.port .Values.metrics.metricsPort }}"
    {{- end }}

    # Graceful shutdown timeout, how long to wait for in-flight requests to complete
    graceful_restart_timeout = "{{ .Values.gracefulRestartTimeout | toString | duration }}"

    {{- if $.Values.global.gitaly.tls.enabled }}
    [tls]
    certificate_path = '/etc/gitlab-secrets/gitaly/gitaly.crt'
    key_path = '/etc/gitlab-secrets/gitaly/gitaly.key'
    {{- end }}

    # Storage configuration
    {{- if .storage }}

    {{- /*
    Passing in "skipStorages=true" below prevents changes in the Gitaly replica counts from modifying
    the contents of the ConfigMap, which would cause existing pods to restart unnecessarily.
    */}}
    {{- if not .skipStorages }}
    {% $storages := coll.Slice {{ include "gitlab.praefect.gitaly.storageNames" . }} %}
    {{- end }}
    {% $hostname := .Env.HOSTNAME | strings.TrimSpace %}
    {% if coll.Has $storages $hostname %}
    [[storage]]
    name = "{% $hostname %}"
    path = "/home/git/repositories"
    {% else %}
    {% printf "Storage for node %q is not present in the storageNames array. Did you use kubectl to scale up? You need to solely use helm for this purpose." $hostname | fail %}
    {% end %}

    {{- else }}

    {{- /*
    Passing in "skipStorages=true" below prevents changes in the Gitaly replica counts from modifying
    the contents of the ConfigMap, which would cause existing pods to restart unnecessarily.
    */}}
    {{- if not .skipStorages }}
    {% $storages := coll.Slice {{ include "gitlab.gitaly.storageNames" . }} %}
    {{- end }}
    {% $index := index (.Env.HOSTNAME | strings.Split "-" | coll.Reverse) 0 | conv.ToInt64 %}
    {% if len $storages | lt $index %}
    [[storage]]
    name = "{% index $storages $index %}"
    path = "/home/git/repositories"
    {% else %}
    {% printf "Storage for node %d is not present in the storageNames array. Did you use kubectl to scale up? You need to solely use helm for this purpose." $index | fail %}
    {% end %}

    {{- end }}

    [logging]
    {{- with .Values.logging }}
    {{- if .level }}
    level = "{{ .level }}"
    {{- end }}
    {{- if .format }}
    format = "{{ .format }}"
    {{- end }}
    {{- if .sentryDsn }}
    sentry_dsn = "{{ .sentryDsn }}"
    {{- end }}
    dir = "/var/log/gitaly"
    {{- if .sentryEnvironment }}
    sentry_environment = "{{ .sentryEnvironment }}"
    {{- end }}
    {{- end }}

    {{- if .Values.prometheus.grpcLatencyBuckets }}
    [prometheus]
    grpc_latency_buckets = {{ .Values.prometheus.grpcLatencyBuckets }}
    {{- end }}

    [auth]
    token = {% file.Read "/etc/gitlab-secrets/gitaly/gitaly_token" | strings.TrimSpace | data.ToJSON %}

    [git]
    use_bundled_binaries = true
    ignore_gitconfig = true
    {{- if .Values.gpgSigning.enabled }}
    signing_key = '/etc/gitlab-secrets/gitaly/signing_key.gpg'
    {{- end }}
    {{- with .Values.git }}
    {{-   if .catFileCacheSize }}
    catfile_cache_size = {{ .catFileCacheSize }}
    {{-   end }}
    {{- end }}
    {{- if .Values.git.config }}
    {{-   range .Values.git.config }}

    [[git.config]]
    key = "{{ .key }}"
    value = "{{ .value }}"
    {{-   end }}
    {{- end }}

    [gitlab-shell]
    # The directory where gitlab-shell is installed
    dir = "/srv/gitlab-shell"

    [gitlab]
    # location of shared secret for GitLab Shell / API interaction
    secret_file = "/etc/gitlab-secrets/shell/.gitlab_shell_secret"
    # URL of API
    url = "{{ template "gitlab.workhorse.url" . }}/"

    [gitlab.http-settings]
    # read_timeout = 300
    # user = someone
    # password = somepass
    # ca_file = /etc/ssl/cert.pem
    # ca_path = /etc/pki/tls/certs

    [hooks]
    # directory containing custom hooks
    custom_hooks_dir = "/home/git/custom_hooks"

    {{- if .Values.shell.concurrency }}
    {{-   range .Values.shell.concurrency }}
    {{-     if and .rpc .maxPerRepo }}
    [[concurrency]]
    rpc = "{{ .rpc }}"
    max_per_repo = {{ .maxPerRepo }}
    {{-     end }}
    {{-   end }}
    {{- end }}

    {{- if .Values.packObjectsCache.enabled }}
    [pack_objects_cache]
    enabled = true
    {{-   with .Values.packObjectsCache }}
    {{-     if .dir }}
    dir = {{ .dir | quote }}
    {{-     end }}
    {{-     if .max_age }}
    max_age = {{ .max_age | quote }}
    {{-     end }}
    {{-     if .min_occurrences }}
    min_occurrences = {{ .min_occurrences }}
    {{-     end }}
    {{-   end }}
    {{- end }}

    {{- if .Values.backup.goCloudUrl }}
    [backup]
    go_cloud_url = "{{ .Values.backup.goCloudUrl }}"
    {{- end }}

    {{- if .Values.cgroups.enabled }}
    {{-   with .Values.cgroups }}
    [cgroups]
    {{-     if .mountpoint }}
    mountpoint = "{{ .mountpoint }}"
    {{-     end }}
    {{-     if .hierarchyRoot }}
    hierarchy_root = {{ .hierarchyRoot | quote }}
    {{-     end }}
    {{-     if .memoryBytes }}
    memory_bytes = {{ .memoryBytes | int64 }}
    {{-     end }}
    {{-     if .cpuShares }}
    cpu_shares = {{ .cpuShares | int64 }}
    {{-     end }}
    {{-     if .cpuQuotaUs }}
    cpu_quota_us = {{ .cpuQuotaUs | int64 }}
    {{-     end }}
    {{-  end }}

    {{-   with .Values.cgroups.repositories }}
    [cgroups.repositories]
    {{-     if .count }}
    count = {{ .count | int64 }}
    {{-     end }}
    {{-     if .memoryBytes }}
    memory_bytes = {{ .memoryBytes | int64 }}
    {{-     end }}
    {{-     if .cpuShares }}
    cpu_shares = {{ .cpuShares | int64 }}
    {{-     end }}
    {{-     if .cpuQuotaUs }}
    cpu_quota_us = {{ .cpuQuotaUs | int64 }}
    {{-     end }}
    {{-     if .maxCgroupsPerRepo }}
    max_cgroups_per_repo = {{ .maxCgroupsPerRepo | int64 }}
    {{-     end }}
    {{-   end }}
    {{- end }}